### PR TITLE
Fixes Issue #11

### PR DESCRIPTION
**Pull request by levanhieu-git**
Res nightmode shows its own up and down arrows. The styles added should
remove them. This is the first time contributing, so please let me know if I am doing anything wrong. Thanks

Here is the result from chrome:

league-css-issue-11

### CODE REVIEW

**Comment by TheEnigmaBlade** [comment]
A couple problems with your fix:
- The changes should go inside `@{nightmode-selector} { ... }` in `darkmode.less` since they're specific to RES night mode.
- The voting arrows are comprised of two parts — bottom and top — where the bottom part is set on `.arrow` and the top part is set on `.arrow::after`. By setting `background` to `none`, you're erasing RES's arrow as well as the bottom part of the arrow.
- It seems arrow dimensions _also_ need to be overridden, as seen in the box models for `.arrow`:
  
  **Normal**
  
  
  **RES night mode**

**Comment by levanhieu-git** [comment]
Thanks for the quick reply. I'll try to fix it up after dinner

**Comment by levanhieu-git** [comment]
OK I tried to fixed what you pointed out. I don't have a very good test set up, but I am just injecting the css into the browser. In chrome, it works just like it does in non res-nightmode now I think.

Also note that it looks like the downvote button colors are very hard to see in nightmode due to its color and opacity (0.5) when not hovered.

**Comment by TheEnigmaBlade** [comment]
I'll accept the request and clean it up, but I have a few tips for when you submit pull requests:
1. You should make sure you're sticking to coding standards of the repository. If the repository uses tabs (like this one) you shouldn't use spaces, and you should ensure your coding style is the same as the repo.
2. Make sure you don't have changes that consist purely of whitespace changes.
3. Logically group your changes together whenever applicable. _Edit: Kinda misread the diff for this one_

I don't want to scare you off from submitting pull requests because it's an awesome thing to do, but programmers _really_ don't like their indentation style changed.

**Comment by levanhieu-git** [comment]
Thank you for the heads up! I didn't even think about it because I'm so used to using my text editor with spaces instead of tabs. I will definitely keep that in mind. I will also review any cleanup code that you do to figure out what I did wrong as well.

Can you explain more about point 3? What did I do wrong in my commits? Was it because I forgot to put the margin-top and made that it's own commit?

Also I noticed two small bugs that are kind of related:

A. When a vote is given (up or down), the image is a bit off in res-nightmode, 
B. When you hover over the downvote (in both res-nightmode and lightmore), it cuts the tip of the down arrow.

For these two issues, should I make new issues for each? And then do pull requests for each?

**Comment by TheEnigmaBlade** [comment]
3 was a mistake. I was reading the diff wrong.

I'm about to fix bug A with the rest of the clean up, and B was fixed with e5ef09418a976de05a4141c63d092cb87ce58cf2 (unless RES is breaking it again).

**Comment by levanhieu-git** [comment]
Ok thanks.

Yup you're right, B is now fixed on the test site. Awesome.

**Pull request merged**
